### ISSUE TITLE
Password reset in active admin broken

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#100] opened 2015-01-15 04:13 UTC
Steps to take:

-  Go to /admin/
- Click on "Forgot your password?"
- Fill in your email address
- Click "Reset my password"
- You should get an error message stating that there was a problem. You should also not receive an email with a password reset.

**Comment by therufs** [comment] 2015-01-15 04:20
Hmm.  AA says you were sent a token.  I bet our mailer's set up
incorrectly.

**Comment by juliaelman** [comment] 2015-01-15 04:21
@therufs thanks for your response! :space_invader: Any ideas on how best to move forward?

**Comment by therufs** [comment] 2015-01-15 04:25
In general, "look at server logs" and "check mailer config" :)  I don't
have a great guess at what the actual problem is, but I'm guessing that
it's "the mail has to come from somewhere and right now it doesn't".

**Comment by juliaelman** [comment] 2015-01-15 04:30
@therufs yup. Just wanted to get your feedback on where things stood on this from where you all left off! Thanks for responding and hope you are doing well! :rainbow:

**Comment by therufs** [comment] 2015-01-15 04:31
'Left off' is probably putting it generously :laughing:

**Comment by kstack7** [comment] 2015-01-27 02:41
I got this working locally. The email server/settings are not in place thus we were never truly sending emails. Added 'config.action_mailer.delivery_method = :smtp' to the config/environments/development.rb file alongside all my personal gmail smtp settings and successfully received the emails. Note: the password does not change once the email is sent; the user is given a link in the email to go change the password. I was able to update my password from there and it worked for the next login.

So! Do we have a particular server or smpt details we want to use for the cause?

**Comment by kstack7** [comment] 2015-01-27 02:42
I'd suggest making an email for this with our "girldevelopit.com" domain name and use google's smtp servers. Definitely easier/reliable!

**Comment by kstack7** [comment] 2015-01-27 04:11
Added the free Mandrill add-on for Heroku alongside Sendgrid (MailChimp fangirl here) and tested both. Sendgrid is reeeally slow in comparison. I vote to use Mandrill, but I left the Sendgrid config commented out if anyone wants to tinker.

Mandrill took care of the domain for now, but we'll want to verify the real the gdi domain in order to up the security/improve deliverability. They provide the necessary changes for the TXT files on the domain, too.

**Comment by kstack7** [comment] 2015-01-31 21:50
All covered and merged in #117 :)

**Closed** 2015-01-31 21:50 UTC
Labels: Bug, Ruby On Rails Needed
